### ISSUE TITLE
Design analytics page UI

### ISSUE THREAD

**Issue by aaronleopold** [camgrodgers/ProductionGraph#24]
SEE [ISSUE](https://github.com/camgrodgers/ProductionGraph/issues/9)

- base setup already there for routing purposes. 
- use dummy data at first to create the charts / graphs / other visual representations of the data returned from rust calls

**Comment by matthewpetela** [comment]
Hey, I commented on the other issue but I thought I would post my response here too. The plan was to graph the relation between the real price and cost-price. 

https://github.com/camgrodgers/ProductionGraph/issues/9#issuecomment-643455419

**Comment by camgrodgers** [comment]
I think this is a duplicate issue, will close for now unless it is actually not a duplicate.
