### ISSUE TITLE
Polish UI

### ISSUE THREAD

**Issue by camgrodgers** [camgrodgers/ProductionGraph#44]
The UI should have more of a theme. The Product display template needs to have the data fields reorganized so that they are grouped logically.

**Comment by aaronleopold** [comment]
**Completed**:

- Real Price, Estimated Cost, and Estimated Labor Time should be emphasized at the top of the Product pages like Estimated Cost currently is.

-  Rest of values should be displayed logically like:
```
        Dollars  |    Hours
direct     $     |     h
indir      $     |     h
```

- History logging button on Product page change to clock
- Quantity is misspelled on Dependency adding modal
-  Logged out view still says "click the create button," instead should say "log in to start adding products"


**Todo**:

- Need logo/icon in top left
    - Logo could depict a graph data structure, a factory, or both?
    - favicon
- Color scheme reconsideration
