### ISSUE TITLE
Button for executing history logging

### ISSUE THREAD

**Issue by camgrodgers** [camgrodgers/ProductionGraph#47]
Price calculation should not be executed every single time the dataset is modified, and instead should be requested explicitly by the user.

**Comment by camgrodgers** [comment]
On second thought, it could actually be good to update the errors and indirect values on every CRUD op.

**Comment by camgrodgers** [comment]
Maybe this should be a button to commit stuff to history.

**Comment by camgrodgers** [comment]
The button should be visible on the Product list page and the individual Product pages, near the top, giving the appearance of a menu item or dash button.

**Comment by matthewpetela** [comment]
![Screenshot_2020-07-26 Production Graph(1)](https://user-images.githubusercontent.com/25089614/88493068-2e210900-cf7d-11ea-9408-59a2d07b67b0.png)
![Screenshot_2020-07-26 Production Graph](https://user-images.githubusercontent.com/25089614/88493069-2e210900-cf7d-11ea-91dd-55900fb8cba0.png)

The API is done. Let me know if this design is okay. After POST it redirects back to the main product or individual product page depending on where you started.

**Comment by camgrodgers** [comment]
Looks good to me.
