### ISSUE TITLE
Create Django view and template for charts/graphs

### ISSUE THREAD

**Issue by matthewpetela** [camgrodgers/ProductionGraph#9]
I'm looking at using [django-chartjs](https://github.com/peopledoc/django-chartjs) for this. It seems to basically be a python wrapper for ChartJS. I was looking at other options for charts/graphs and they didn't seem that good.

**Comment by camgrodgers** [comment]
This could be cool for the prototype, what charts are you thinking of making? The data won't have a history, so we are a bit limited in what we can graph for the prototype. But these come to mind (just ideas) for graphs:
- Relation between real price and cost-price to show whether or not there's a correlation, and what the difference (profit) is.
- Relation between total labor time and cost-price to see how much wages and labor time correlate. 
- A visual representation of the number of dependencies that products have. Like which ones have the most dependencies, which are most depended-on, relation between number of dependencies and indirect costs (labor and cost_price)
- ...

**Comment by matthewpetela** [comment]
Hey sorry, I took so long to respond. I've been quite busy. I was likely going to just use them as a demonstration for now. But, I think graphing the relation between the real price and cost-price would be a good idea.

**Comment by aaronleopold** [comment]
No worries, sounds good. Until the Dependency model is added/used in the Django views + templates it'll have to be demonstrative/dummy data anyways.
